name: Spellcheck Action
on: push

jobs:
  build:
    name: Spellcheck
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: pavelskipenes/spellcheck-github-actions@master
      name: Spellcheck
      with:
        config_path: ".config/.spellcheck.yml"
